In [1]:
import numpy as np

In [2]:
data = [
    [30, 1, 3],
    [20, 0, 8],
    [25, 0, 6],
    [15, 1, 7]
]

### К нашей температуре прибавть 5

In [5]:
t = []
r = []
h = []

for day in data:
    t.append(day[0])
    r.append(day[1])
    h.append(day[2])

    print (t)
    print (r)
    print (h)

[30]
[1]
[3]
[30, 20]
[1, 0]
[3, 8]
[30, 20, 25]
[1, 0, 0]
[3, 8, 6]
[30, 20, 25, 15]
[1, 0, 0, 1]
[3, 8, 6, 7]


In [ ]:
new_t =[]
for i in t:
    new_t.append(i+5)

    print(new_t)

[35]
[35, 25]
[35, 25, 30]
[35, 25, 30, 20]


### Давай сдлеаем с помощью numpy

In [8]:
data = np.array([
    [30, 1, 3],
    [20, 0, 8],
    [25, 0, 6],
    [15, 1, 7]
])

In [9]:
print(data[:,0]+5)

[35 25 30 20]


#### (":  - означает ВСЕ строки")
#### ("0  - означает столбец 0 (первый столбец)")

#### ("data1[:, 0] = ВСЕ строки, столбец 0")
#### ("data1[0, :] = строка 0, ВСЕ столбцы")
#### ("data1[1, 2] = строка 1, столбец 2 (одно число)")

### Хочу найти жаркий день где темпертару будет > 22, с рекламой 

In [11]:
t_hot = data[:,0] > 22
r_day = data[:,1] == 1

In [13]:
combinate = t_hot & r_day
print(combinate)

[ True False False False]


In [14]:
result = data[combinate]
result 

array([[30,  1,  3]])

In [15]:
X = np.array([
    [1, 2, 3],
    [4, 6, 7],
    [13, 8, 5],
    [1, 12, 3]
])

In [17]:
w_all = np.array([2, 4, 6])

In [18]:
result = X@w_all

In [19]:
print(result)

[28 74 88 68]


In [21]:
data.shape

(4, 3)

In [23]:
data.ndim

2

In [26]:
result = np.sum(data, axis =0)
result

array([90,  2, 24])

In [27]:
data.T

array([[30, 20, 25, 15],
       [ 1,  0,  0,  1],
       [ 3,  8,  6,  7]])